// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmAKdeBaRNkZ7mWOUT-exOSA9J3CK-VPM',
    appId: '1:176264592076:android:4ee311d458a51ffa64a069',
    messagingSenderId: '176264592076',
    projectId: 'sinacare-efbbe',
    storageBucket: 'sinacare-efbbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_yHOdaw6k7c-YJ5MdCFV4LV4rCr2_I9U',
    appId: '1:176264592076:ios:b82c63d1fa85c1be64a069',
    messagingSenderId: '176264592076',
    projectId: 'sinacare-efbbe',
    storageBucket: 'sinacare-efbbe.firebasestorage.app',
    androidClientId: '176264592076-f2prvpgcta20mo2pariqvq0tn1rr62fi.apps.googleusercontent.com',
    iosClientId: '176264592076-t1ofsvsukhunt1bbo6p3fvtdr5kkm1uo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
